[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "agent"
path = "src/agent.rs"

[dependencies]
actix-cors = "0.7.1"
actix-governor = "0.8.0"
actix-web = "4"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.37.0", features = ["sync", "macros", "rt"] }
futures-util = "0.3.30"
actix-web-lab = "0.20.2"
sysinfo = "0.30.5"
reqwest = { version = "0.11.23", features = ["json", "blocking"] }
mpris = { version = "2.0.1", optional = true }
chrono = "0.4.44"

# To build agent we now gotta do `cargo build --bin agent --features agent`
[features]
agent = ["dep:mpris"]
