[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-governor = "0.8.0"
actix-web = "4"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
