services:
    kony_backend:
        container_name: kony_backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "10.0.0.19:8115:8115"
        environment:
            - API_KEY=$API_KEY
        volumes:
            - .:/usr/src/app
        command: cargo run --release
