import { FsNode } from '@/lib/types';

export const filesystem: FsNode = {
    name: '/',
    type: 'directory',
    ownership: 'root/root',
    permissions: '0755/drwxr-xr-x',
    size: 4096,
    timestamp: {
        shortHand: 'Jul 7 14:30',
        access: '2025-07-11 16:10:01.435201480 +0700',
        modify: '2025-07-07 14:30:34.747759829 +0700',
        change: '2025-07-07 14:30:34.747759829 +0700',
        birth: '2024-09-05 20:07:26.000000000 +0700',
    },
    children: [
        {
            name: 'bin',
            type: 'file',
            ownership: 'root/root',
            permissions: 'lrwxrwxrwx',
            size: 7,
            timestamp: {
                shortHand: 'May 4 02:26',
            },
        },
        {
            name: 'boot',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwxr-xr-x',
            size: 4096,
            timestamp: {
                shortHand: 'Jan 1 1970',
            },
        },
        {
            name: 'dev',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwxr-xr-x',
            size: 4460,
            timestamp: {
                shortHand: 'Jul 11 2025',
            },
        },
        {
            name: 'etc',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwxr-xr-x',
            size: 4096,
            timestamp: {
                shortHand: 'Jul 11 12:57',
            },
        },
        {
            name: 'home',
            type: 'directory',
            ownership: 'root/root',
            permissions: '0755/drwxr-xr-x',
            size: 4096,
            timestamp: {
                shortHand: 'Sep 5 2024',
                access: '2025-07-11 13:01:19.014682183 +0700',
                modify: '2024-09-05 20:13:54.206874357 +0700',
                change: '2024-09-05 20:13:54.206874357 +0700',
                birth: '2024-09-05 20:12:13.438896585 +0700',
            },
            children: [
                {
                    name: 'kony',
                    type: 'directory',
                    ownership: 'kony/kony',
                    permissions: '0700/drwx------',
                    size: 4096,
                    timestamp: {
                        shortHand: 'Jul 11 17:09',
                        access: '2025-07-11 17:09:44.154695929 +0700',
                        modify: '2025-07-11 17:09:44.134695077 +0700',
                        change: '2025-07-11 17:09:44.134695077 +0700',
                        birth: '2024-09-05 20:13:54.206874357 +0700',
                    },
                    children: [
                        {
                            name: 'a.out',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 0,
                            timestamp: {
                                shortHand: 'May 29 17:40',
                                access: '2025-05-29 17:40:23.361952608 +0700',
                                modify: '2025-05-29 17:40:23.361952608 +0700',
                                change: '2025-05-29 17:40:23.361952608 +0700',
                                birth: '2025-05-29 17:40:23.361952608 +0700',
                            },
                        },
                        {
                            name: '.bun',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 10 2024',
                            },
                        },
                        {
                            name: '.cache',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Jul 8 17:05',
                            },
                        },
                        {
                            name: '.cargo',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Jul 10 14:50',
                            },
                        },
                        {
                            name: '.config',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Jun 9 20:18',
                            },
                        },
                        {
                            name: 'Desktop',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Dec 20 2024',
                                access: '2025-07-11 17:09:44.188697376 +0700',
                                modify: '2024-12-20 18:15:13.766682733 +0700',
                                change: '2024-12-20 18:15:13.766682733 +0700',
                                birth: '2024-09-05 20:42:39.722960912 +0700',
                            },
                            children: [
                                {
                                    name: 'code.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 441411,
                                    timestamp: {
                                        shortHand: 'Dec 20 2024',
                                    },
                                },
                            ],
                        },
                        {
                            name: 'dir_info.txt',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 9607,
                            timestamp: {
                                shortHand: 'Jul 11 17:09',
                                access: '2025-07-11 17:09:44.134695077 +0700',
                                modify: '2025-07-11 17:09:44.199697845 +0700',
                                change: '2025-07-11 17:09:44.199697845 +0700',
                                birth: '2025-07-11 17:09:44.134695077 +0700',
                            },
                        },
                        {
                            name: 'discord.sh',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0755/-rwxr-xr-x',
                            size: 1650,
                            timestamp: {
                                shortHand: 'Apr 18 21:00',
                                access: '2025-07-10 15:30:03.700975919 +0700',
                                modify: '2025-04-18 21:00:03.493548233 +0700',
                                change: '2025-04-18 21:00:03.493548233 +0700',
                                birth: '2025-04-18 21:00:03.492548189 +0700',
                            },
                        },
                        {
                            name: '.docker',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Jun 13 19:25',
                            },
                        },
                        {
                            name: 'Documents',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'May 28 22:26',
                                access: '2025-07-11 13:01:19.014682183 +0700',
                                modify: '2025-05-28 22:26:37.551374297 +0700',
                                change: '2025-05-28 22:26:37.551374297 +0700',
                                birth: '2024-09-05 20:42:39.722960912 +0700',
                            },
                            children: [
                                {
                                    name: 'GitHub',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Jun 26 15:53',
                                    },
                                },
                            ],
                        },
                        {
                            name: '.dotfiles',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'May 30 14:18',
                            },
                        },
                        {
                            name: 'Downloads',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Jul 11 15:07',
                                access: '2025-07-11 17:09:44.215698526 +0700',
                                modify: '2025-07-11 15:07:31.059805042 +0700',
                                change: '2025-07-11 15:07:31.059805042 +0700',
                                birth: '2024-09-05 20:42:39.722960912 +0700',
                            },
                            children: [
                                {
                                    name: '2025-02-03-2.log',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 128073,
                                    timestamp: {
                                        shortHand: 'Feb 3 20:20',
                                    },
                                },
                                {
                                    name: '2025-02-03-2.log.gz',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 12914,
                                    timestamp: {
                                        shortHand: 'Feb 3 20:20',
                                    },
                                },
                                {
                                    name: '35020247_8262064(1).svg',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 114648,
                                    timestamp: {
                                        shortHand: 'Jun 3 00:18',
                                    },
                                },
                                {
                                    name: '3.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 122262,
                                    timestamp: {
                                        shortHand: 'Jun 25 20:28',
                                    },
                                },
                                {
                                    name: '4147bc7a93934d87.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1072,
                                    timestamp: {
                                        shortHand: 'Jan 25 18:29',
                                    },
                                },
                                {
                                    name: '4.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 123060,
                                    timestamp: {
                                        shortHand: 'Jun 25 20:28',
                                    },
                                },
                                {
                                    name: '79127ddbc1ba67b2.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 2713,
                                    timestamp: {
                                        shortHand: 'Jan 23 20:33',
                                    },
                                },
                                {
                                    name: 'a.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 511,
                                    timestamp: {
                                        shortHand: 'Mar 30 15:38',
                                    },
                                },
                                {
                                    name: 'ban.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 460931,
                                    timestamp: {
                                        shortHand: 'Oct 12 2024',
                                    },
                                },
                                {
                                    name: 'bar1(1).jpg',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 451909,
                                    timestamp: {
                                        shortHand: 'Nov 18 2024',
                                    },
                                },
                                {
                                    name: 'bar1.jpg',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 50612,
                                    timestamp: {
                                        shortHand: 'Nov 18 2024',
                                    },
                                },
                                {
                                    name: 'bar2.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 347669,
                                    timestamp: {
                                        shortHand: 'Nov 18 2024',
                                    },
                                },
                                {
                                    name: 'bar2_upscaled.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1260624,
                                    timestamp: {
                                        shortHand: 'Nov 18 2024',
                                    },
                                },
                                {
                                    name: 'booking.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 6332742,
                                    timestamp: {
                                        shortHand: 'Feb 20 16:13',
                                    },
                                },
                                {
                                    name: 'bss',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Jun 29 16:22',
                                    },
                                },
                                {
                                    name: 'bun-linux-x64-baseline.zip',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 38291778,
                                    timestamp: {
                                        shortHand: 'Jul 11 15:07',
                                    },
                                },
                                {
                                    name: 'b.zip',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 31169289,
                                    timestamp: {
                                        shortHand: 'Jan 19 18:40',
                                    },
                                },
                                {
                                    name: 'Calculus.pdf',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 40643894,
                                    timestamp: {
                                        shortHand: 'Mar 28 17:20',
                                    },
                                },
                                {
                                    name: 'cancel.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 4529096,
                                    timestamp: {
                                        shortHand: 'Feb 20 16:39',
                                    },
                                },
                                {
                                    name: 'cbss.zip',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 308316913,
                                    timestamp: {
                                        shortHand: 'Jun 30 18:29',
                                    },
                                },
                                {
                                    name: 'cinemamod-linux_amd64-1.0.7-1.21.1(1).jar',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 121144901,
                                    timestamp: {
                                        shortHand: 'Dec 30 2024',
                                    },
                                },
                                {
                                    name: 'clown.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1491,
                                    timestamp: {
                                        shortHand: 'Jan 21 22:04',
                                    },
                                },
                                {
                                    name: 'dotfiles-main.zip',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 10364,
                                    timestamp: {
                                        shortHand: 'Apr 1 22:44',
                                    },
                                },
                                {
                                    name: 'Doxium app_files',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Oct 24 2024',
                                    },
                                },
                                {
                                    name: 'Doxium app.html',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 101606,
                                    timestamp: {
                                        shortHand: 'Oct 24 2024',
                                    },
                                },
                                {
                                    name: 'DX(1).ico',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1071,
                                    timestamp: {
                                        shortHand: 'Dec 28 2024',
                                    },
                                },
                                {
                                    name: 'DX.ico',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1071,
                                    timestamp: {
                                        shortHand: 'Dec 28 2024',
                                    },
                                },
                                {
                                    name: 'DX.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1179,
                                    timestamp: {
                                        shortHand: 'Dec 28 2024',
                                    },
                                },
                                {
                                    name: 'favicon(1).ico',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 4286,
                                    timestamp: {
                                        shortHand: 'Feb 20 15:38',
                                    },
                                },
                                {
                                    name: 'favicon.ico',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1598,
                                    timestamp: {
                                        shortHand: 'Dec 28 2024',
                                    },
                                },
                                {
                                    name: 'favicon.svg',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 41986,
                                    timestamp: {
                                        shortHand: 'Sep 11 2024',
                                    },
                                },
                                {
                                    name: 'ff2ce3a211d784b7.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1006,
                                    timestamp: {
                                        shortHand: 'Jan 23 20:31',
                                    },
                                },
                                {
                                    name: 'glad.zip',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1785118,
                                    timestamp: {
                                        shortHand: 'Mar 30 00:49',
                                    },
                                },
                                {
                                    name: 'image.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 2342,
                                    timestamp: {
                                        shortHand: 'Jan 23 20:21',
                                    },
                                },
                                {
                                    name: 'konyogony .dotfiles main .config-hypr.zip',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 21043578,
                                    timestamp: {
                                        shortHand: 'Apr 1 22:41',
                                    },
                                },
                                {
                                    name: 'launcher-1.0.jar',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 6948752,
                                    timestamp: {
                                        shortHand: 'Sep 15 2024',
                                    },
                                },
                                {
                                    name: 'letter.jpg',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 652938,
                                    timestamp: {
                                        shortHand: 'Oct 9 2024',
                                    },
                                },
                                {
                                    name: 'Logo for doxium',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Dec 28 2024',
                                    },
                                },
                                {
                                    name: 'Logo for doxium.zip',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 3524,
                                    timestamp: {
                                        shortHand: 'Dec 28 2024',
                                    },
                                },
                                {
                                    name: 'logo.jpg',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 49980,
                                    timestamp: {
                                        shortHand: 'Nov 24 2024',
                                    },
                                },
                                {
                                    name: 'mc.jar',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 9612170,
                                    timestamp: {
                                        shortHand: 'Jan 27 18:36',
                                    },
                                },
                                {
                                    name: 'metal.json',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 551,
                                    timestamp: {
                                        shortHand: 'Jan 19 20:41',
                                    },
                                },
                                {
                                    name: 'old.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1590,
                                    timestamp: {
                                        shortHand: 'Jan 26 17:15',
                                    },
                                },
                                {
                                    name: 'post_install.sh',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rwxr-xr-x',
                                    size: 1896,
                                    timestamp: {
                                        shortHand: 'Mar 13 09:52',
                                    },
                                },
                                {
                                    name: 'post_uninstall.sh',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rwxr-xr-x',
                                    size: 1878,
                                    timestamp: {
                                        shortHand: 'Mar 13 09:52',
                                    },
                                },
                                {
                                    name: 'protein_bar.glb',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 2265256,
                                    timestamp: {
                                        shortHand: 'Nov 23 2024',
                                    },
                                },
                                {
                                    name: 'replay(1).ttrm',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 115892,
                                    timestamp: {
                                        shortHand: 'Dec 17 2024',
                                    },
                                },
                                {
                                    name: 'replay.ttrm',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 2656,
                                    timestamp: {
                                        shortHand: 'Sep 14 2024',
                                    },
                                },
                                {
                                    name: 'rp.zip',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 10137,
                                    timestamp: {
                                        shortHand: 'Mar 4 18:47',
                                    },
                                },
                                {
                                    name: 'service',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwx------',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Mar 13 16:57',
                                    },
                                },
                                {
                                    name: 's.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1554,
                                    timestamp: {
                                        shortHand: 'Jan 25 18:40',
                                    },
                                },
                                {
                                    name: 'test.zip',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 60901787,
                                    timestamp: {
                                        shortHand: 'Mar 24 21:24',
                                    },
                                },
                                {
                                    name: 'tile1.jpg',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 104704,
                                    timestamp: {
                                        shortHand: 'Jan 19 20:00',
                                    },
                                },
                                {
                                    name: 'tile1.png',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 2147,
                                    timestamp: {
                                        shortHand: 'Jan 19 20:40',
                                    },
                                },
                                {
                                    name: 'Untitled-2025-01-15-2237.excalidraw',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 7655728,
                                    timestamp: {
                                        shortHand: 'Jan 15 22:37',
                                    },
                                },
                                {
                                    name: 'video-v3.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 77013076,
                                    timestamp: {
                                        shortHand: 'Nov 25 2024',
                                    },
                                },
                            ],
                        },
                        {
                            name: 'doxium.txt',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 1627,
                            timestamp: {
                                shortHand: 'Sep 24 2024',
                                access: '2025-04-17 01:42:06.141333681 +0700',
                                modify: '2024-09-24 17:25:02.504214448 +0700',
                                change: '2024-09-24 17:25:02.504214448 +0700',
                                birth: '2024-09-24 17:23:09.234976432 +0700',
                            },
                        },
                        {
                            name: 'get_info.sh',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0755/-rwxr-xr-x',
                            size: 531,
                            timestamp: {
                                shortHand: 'Jul 11 17:09',
                                access: '2025-07-11 17:09:44.133695034 +0700',
                                modify: '2025-07-11 17:09:29.710080922 +0700',
                                change: '2025-07-11 17:09:38.918472983 +0700',
                                birth: '2025-07-11 17:09:29.710080922 +0700',
                            },
                        },
                        {
                            name: '.gitconfig',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 367,
                            timestamp: {
                                shortHand: 'Mar 28 23:31',
                            },
                        },
                        {
                            name: '.git-credentials',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-------',
                            size: 123,
                            timestamp: {
                                shortHand: 'Jul 11 15:05',
                            },
                        },
                        {
                            name: 'i_use_arch_btw.sh',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0755/-rwxr-xr-x',
                            size: 1185,
                            timestamp: {
                                shortHand: 'Nov 23 2024',
                                access: '2025-07-07 14:30:33.320696141 +0700',
                                modify: '2024-11-23 14:16:49.447447757 +0700',
                                change: '2024-11-23 14:16:49.637453494 +0700',
                                birth: '2024-11-23 14:16:49.447447757 +0700',
                            },
                        },
                        {
                            name: '.java',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 6 2024',
                            },
                        },
                        {
                            name: '.local',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwx------',
                            size: 4096,
                            timestamp: {
                                shortHand: 'May 28 22:16',
                            },
                        },
                        {
                            name: 'lua',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Mar 27 19:02',
                                access: '2025-07-11 13:33:26.002524519 +0700',
                                modify: '2025-03-27 19:02:54.649407076 +0700',
                                change: '2025-03-27 19:02:54.649407076 +0700',
                                birth: '2025-03-27 19:02:54.649407076 +0700',
                            },
                            children: [],
                        },
                        {
                            name: '.minecraft',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Jul 8 19:11',
                            },
                        },
                        {
                            name: '.mozilla',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwx------',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 5 2024',
                            },
                        },
                        {
                            name: 'mpvpaper',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Dec 3 2024',
                                access: '2025-07-11 17:09:44.269700825 +0700',
                                modify: '2024-12-03 17:01:20.263449065 +0700',
                                change: '2024-12-03 17:01:20.263449065 +0700',
                                birth: '2024-12-03 17:01:18.080046886 +0700',
                            },
                            children: [
                                {
                                    name: 'build',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Dec 3 2024',
                                    },
                                },
                                {
                                    name: '.git',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Dec 3 2024',
                                    },
                                },
                                {
                                    name: 'inc',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Dec 3 2024',
                                    },
                                },
                                {
                                    name: 'LICENSE',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 35149,
                                    timestamp: {
                                        shortHand: 'Dec 3 2024',
                                    },
                                },
                                {
                                    name: 'meson.build',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1506,
                                    timestamp: {
                                        shortHand: 'Dec 3 2024',
                                    },
                                },
                                {
                                    name: 'mpvpaper.man',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 4586,
                                    timestamp: {
                                        shortHand: 'Dec 3 2024',
                                    },
                                },
                                {
                                    name: 'proto',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Dec 3 2024',
                                    },
                                },
                                {
                                    name: 'README.md',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1742,
                                    timestamp: {
                                        shortHand: 'Dec 3 2024',
                                    },
                                },
                                {
                                    name: 'src',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Dec 3 2024',
                                    },
                                },
                            ],
                        },
                        {
                            name: 'Music',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Apr 17 13:42',
                                access: '2025-07-11 17:09:44.273700996 +0700',
                                modify: '2025-04-17 13:42:27.370997427 +0700',
                                change: '2025-04-17 13:42:27.370997427 +0700',
                                birth: '2025-04-17 13:42:27.370997427 +0700',
                            },
                            children: [],
                        },
                        {
                            name: 'nicknames.txt',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 7047,
                            timestamp: {
                                shortHand: 'Jan 25 21:53',
                                access: '2025-03-28 19:44:32.236258130 +0700',
                                modify: '2025-01-25 21:53:08.936590022 +0700',
                                change: '2025-01-25 21:53:08.936590022 +0700',
                                birth: '2025-01-25 21:53:08.936590022 +0700',
                            },
                        },
                        {
                            name: '.npm',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Dec 17 2024',
                            },
                        },
                        {
                            name: '.npmrc',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-------',
                            size: 74,
                            timestamp: {
                                shortHand: 'Dec 28 2024',
                            },
                        },
                        {
                            name: '.nv',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwx------',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 5 2024',
                            },
                        },
                        {
                            name: '.nvm',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Oct 21 2024',
                            },
                        },
                        {
                            name: '.oh-my-zsh',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Jun 20 23:50',
                            },
                        },
                        {
                            name: '.openjfx',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 15 2024',
                            },
                        },
                        {
                            name: 'output.raw',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 105408000,
                            timestamp: {
                                shortHand: 'Apr 9 18:59',
                                access: '2025-04-09 18:59:17.753061327 +0700',
                                modify: '2025-04-09 18:59:17.375044998 +0700',
                                change: '2025-04-09 18:59:17.375044998 +0700',
                                birth: '2025-04-09 18:59:12.366828648 +0700',
                            },
                        },
                        {
                            name: 'output.txt',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 32571655,
                            timestamp: {
                                shortHand: 'Apr 14 15:30',
                                access: '2025-04-14 15:30:18.902237733 +0700',
                                modify: '2025-04-14 15:30:13.455033520 +0700',
                                change: '2025-04-14 15:30:13.455033520 +0700',
                                birth: '2025-04-14 15:30:12.312990466 +0700',
                            },
                        },
                        {
                            name: 'paru',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Oct 12 2024',
                                access: '2025-07-11 17:09:44.296701975 +0700',
                                modify: '2024-10-12 18:52:51.000262614 +0700',
                                change: '2024-10-12 18:52:51.000262614 +0700',
                                birth: '2024-10-12 18:52:36.056120427 +0700',
                            },
                            children: [
                                {
                                    name: '.git',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Oct 12 2024',
                                    },
                                },
                                {
                                    name: 'paru-2.0.4.tar.gz',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 8257932,
                                    timestamp: {
                                        shortHand: 'Oct 12 2024',
                                    },
                                },
                                {
                                    name: 'pkg',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'd--x--x--x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Oct 12 2024',
                                    },
                                },
                                {
                                    name: 'PKGBUILD',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1679,
                                    timestamp: {
                                        shortHand: 'Oct 12 2024',
                                    },
                                },
                                {
                                    name: 'src',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Oct 12 2024',
                                    },
                                },
                                {
                                    name: '.SRCINFO',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 651,
                                    timestamp: {
                                        shortHand: 'Oct 12 2024',
                                    },
                                },
                            ],
                        },
                        {
                            name: 'Pictures',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Apr 17 01:36',
                                access: '2025-07-11 17:09:44.305702358 +0700',
                                modify: '2025-04-17 01:36:33.989450379 +0700',
                                change: '2025-04-17 01:36:33.989450379 +0700',
                                birth: '2024-09-05 20:42:39.722960912 +0700',
                            },
                            children: [
                                {
                                    name: 'Screenshots',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 65536,
                                    timestamp: {
                                        shortHand: 'Jul 11 15:07',
                                    },
                                },
                            ],
                        },
                        {
                            name: '.profile',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 21,
                            timestamp: {
                                shortHand: 'Sep 7 2024',
                            },
                        },
                        {
                            name: 'Public',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 5 2024',
                                access: '2025-07-11 13:33:26.002524519 +0700',
                                modify: '2024-09-05 20:42:39.722960912 +0700',
                                change: '2024-09-05 20:42:39.722960912 +0700',
                                birth: '2024-09-05 20:42:39.722960912 +0700',
                            },
                            children: [],
                        },
                        {
                            name: '.pyenv',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Mar 26 20:33',
                            },
                        },
                        {
                            name: '.python_history',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 0,
                            timestamp: {
                                shortHand: 'Jun 13 19:19',
                            },
                        },
                        {
                            name: 'README.md',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 489,
                            timestamp: {
                                shortHand: 'Apr 17 03:22',
                                access: '2025-04-17 03:23:33.012916946 +0700',
                                modify: '2025-04-17 03:22:16.750681660 +0700',
                                change: '2025-04-17 03:22:16.750681660 +0700',
                                birth: '2025-04-17 03:22:16.735681030 +0700',
                            },
                        },
                        {
                            name: 'recording.mkv',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 8176621,
                            timestamp: {
                                shortHand: 'Apr 14 15:21',
                                access: '2025-04-15 23:07:45.637250420 +0700',
                                modify: '2025-04-14 15:21:05.302789629 +0700',
                                change: '2025-04-14 15:21:05.302789629 +0700',
                                birth: '2025-04-14 15:20:17.506256108 +0700',
                            },
                        },
                        {
                            name: '.rustup',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 7 2024',
                            },
                        },
                        {
                            name: 'screen.mp4',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 1293305,
                            timestamp: {
                                shortHand: 'Apr 9 18:57',
                                access: '2025-05-29 19:00:09.805198858 +0700',
                                modify: '2025-04-09 18:57:55.532510044 +0700',
                                change: '2025-04-09 18:57:55.532510044 +0700',
                                birth: '2025-04-09 18:57:53.909439953 +0700',
                            },
                        },
                        {
                            name: 'screenshot.png',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 41759,
                            timestamp: {
                                shortHand: 'Apr 14 17:02',
                                access: '2025-05-29 19:00:04.250407433 +0700',
                                modify: '2025-04-14 17:02:21.036129993 +0700',
                                change: '2025-04-14 17:02:21.036129993 +0700',
                                birth: '2025-04-14 16:54:37.084022638 +0700',
                            },
                        },
                        {
                            name: '.spicetify',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'May 20 19:42',
                            },
                        },
                        {
                            name: '.ssh',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwx------',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Jun 24 20:00',
                            },
                        },
                        {
                            name: '.surrealdb',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 7 2024',
                            },
                        },
                        {
                            name: 'Templates',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 5 2024',
                                access: '2025-07-11 13:33:26.003524562 +0700',
                                modify: '2024-09-05 20:42:39.722960912 +0700',
                                change: '2024-09-05 20:42:39.722960912 +0700',
                                birth: '2024-09-05 20:42:39.722960912 +0700',
                            },
                            children: [],
                        },
                        {
                            name: '.tetris.scores',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 272,
                            timestamp: {
                                shortHand: 'May 29 19:35',
                            },
                        },
                        {
                            name: 'text.txt',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 29,
                            timestamp: {
                                shortHand: 'Jul 2 02:23',
                                access: '2025-07-02 02:23:12.796910499 +0700',
                                modify: '2025-07-02 02:23:10.820821961 +0700',
                                change: '2025-07-02 02:23:10.820821961 +0700',
                                birth: '2025-07-02 02:23:10.819821916 +0700',
                            },
                        },
                        {
                            name: '.themes',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 5 2024',
                            },
                        },
                        {
                            name: '.var',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Sep 6 2024',
                            },
                        },
                        {
                            name: 'vencord_installer.sh',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0755/-rwxr-xr-x',
                            size: 6692864,
                            timestamp: {
                                shortHand: 'Jul 11 12:57',
                                access: '2025-07-11 12:57:59.618510013 +0700',
                                modify: '2025-07-11 12:57:59.587508382 +0700',
                                change: '2025-07-11 12:57:59.599509013 +0700',
                                birth: '2025-03-02 16:51:55.862346442 +0700',
                            },
                        },
                        {
                            name: 'Videos',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: '0755/drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Apr 17 01:46',
                                access: '2025-07-11 17:09:44.346704104 +0700',
                                modify: '2025-04-17 01:46:19.033528544 +0700',
                                change: '2025-04-17 01:46:19.033528544 +0700',
                                birth: '2024-09-05 20:42:39.722960912 +0700',
                            },
                            children: [
                                {
                                    name: '2025-03-30 14-50-25.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 19873952,
                                    timestamp: {
                                        shortHand: 'Mar 30 14:51',
                                    },
                                },
                                {
                                    name: '2025-03-30 15-40-16.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 19252148,
                                    timestamp: {
                                        shortHand: 'Mar 30 15:40',
                                    },
                                },
                                {
                                    name: '2025-03-30 15-41-19.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 21629036,
                                    timestamp: {
                                        shortHand: 'Mar 30 15:42',
                                    },
                                },
                                {
                                    name: '2025-04-09 15-29-04.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1667868,
                                    timestamp: {
                                        shortHand: 'Apr 9 15:29',
                                    },
                                },
                                {
                                    name: '2025-04-13 18-02-23.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 12445298,
                                    timestamp: {
                                        shortHand: 'Apr 13 18:02',
                                    },
                                },
                                {
                                    name: '2025-04-13 18-03-47.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 16002375,
                                    timestamp: {
                                        shortHand: 'Apr 13 18:04',
                                    },
                                },
                                {
                                    name: '2025-04-13 18-14-32.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 46955742,
                                    timestamp: {
                                        shortHand: 'Apr 13 18:16',
                                    },
                                },
                                {
                                    name: '2025-04-14 15-09-23.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 771661,
                                    timestamp: {
                                        shortHand: 'Apr 14 15:09',
                                    },
                                },
                                {
                                    name: 'output2.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 5737471,
                                    timestamp: {
                                        shortHand: 'Mar 30 14:56',
                                    },
                                },
                                {
                                    name: 'output3.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 5763991,
                                    timestamp: {
                                        shortHand: 'Mar 30 15:26',
                                    },
                                },
                                {
                                    name: 'output4.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 2719921,
                                    timestamp: {
                                        shortHand: 'Mar 30 15:27',
                                    },
                                },
                                {
                                    name: 'output6.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 15505257,
                                    timestamp: {
                                        shortHand: 'Mar 30 15:43',
                                    },
                                },
                                {
                                    name: 'output7.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 12748349,
                                    timestamp: {
                                        shortHand: 'Mar 30 15:44',
                                    },
                                },
                                {
                                    name: 'output.mkv',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 6950571,
                                    timestamp: {
                                        shortHand: 'Mar 30 15:31',
                                    },
                                },
                                {
                                    name: 'output.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 8069918,
                                    timestamp: {
                                        shortHand: 'Mar 30 14:53',
                                    },
                                },
                                {
                                    name: 'rec2.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 12926142,
                                    timestamp: {
                                        shortHand: 'Mar 30 15:06',
                                    },
                                },
                                {
                                    name: 'rec3.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 9855419,
                                    timestamp: {
                                        shortHand: 'Mar 30 15:22',
                                    },
                                },
                                {
                                    name: 'Replay 2025-04-09 15-30-40.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 1859230,
                                    timestamp: {
                                        shortHand: 'Apr 9 15:30',
                                    },
                                },
                                {
                                    name: 'Replay 2025-04-09 15-34-55.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 54760737,
                                    timestamp: {
                                        shortHand: 'Apr 9 15:34',
                                    },
                                },
                                {
                                    name: 'Replay 2025-04-10 19-56-25.mp4',
                                    type: 'file',
                                    ownership: 'kony/kony',
                                    permissions: '-rw-r--r--',
                                    size: 943610,
                                    timestamp: {
                                        shortHand: 'Apr 10 19:56',
                                    },
                                },
                                {
                                    name: 'wallpapers',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Mar 30 14:15',
                                    },
                                },
                                {
                                    name: 'wayclip',
                                    type: 'directory',
                                    ownership: 'kony/kony',
                                    permissions: 'drwxr-xr-x',
                                    size: 4096,
                                    timestamp: {
                                        shortHand: 'Apr 8 22:11',
                                    },
                                },
                            ],
                        },
                        {
                            name: '.viminfo',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-------',
                            size: 1668,
                            timestamp: {
                                shortHand: 'Sep 28 2024',
                            },
                        },
                        {
                            name: '.wakatime',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Jul 4 18:29',
                            },
                        },
                        {
                            name: '.wakatime.cfg',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 101,
                            timestamp: {
                                shortHand: 'Apr 10 14:52',
                            },
                        },
                        {
                            name: 'wave.gif',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 13024949,
                            timestamp: {
                                shortHand: 'Apr 1 15:41',
                                access: '2025-04-15 23:07:45.798257234 +0700',
                                modify: '2025-04-01 15:41:48.000000000 +0700',
                                change: '2025-04-01 22:42:28.313276873 +0700',
                                birth: '2025-04-01 22:42:28.305803691 +0700',
                            },
                        },
                        {
                            name: 'waybar.zip',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '0644/-rw-r--r--',
                            size: 8937,
                            timestamp: {
                                shortHand: 'Apr 1 20:28',
                                access: '2025-04-01 20:29:08.773392958 +0700',
                                modify: '2025-04-01 20:28:00.973421310 +0700',
                                change: '2025-04-01 20:28:00.973421310 +0700',
                                birth: '2025-04-01 20:28:00.972421266 +0700',
                            },
                        },
                        {
                            name: 'windows.sh',
                            type: 'file',
                            ownership: 'root/root',
                            permissions: '0755/-rwxr-xr-x',
                            size: 44,
                            timestamp: {
                                shortHand: 'Sep 15 2024',
                                access: '2025-07-10 19:32:34.464501062 +0700',
                                modify: '2024-09-15 17:16:09.832036676 +0700',
                                change: '2024-09-15 17:16:26.309391644 +0700',
                                birth: '2024-09-15 17:16:09.832036676 +0700',
                            },
                        },
                        {
                            name: '.yarn',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwxr-xr-x',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Dec 29 2024',
                            },
                        },
                        {
                            name: '.yarnrc',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 116,
                            timestamp: {
                                shortHand: 'Dec 29 2024',
                            },
                        },
                        {
                            name: '.zcompdump',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 50364,
                            timestamp: {
                                shortHand: 'Apr 17 03:15',
                            },
                        },
                        {
                            name: '.zcompdump-archlinux-5.9',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 50717,
                            timestamp: {
                                shortHand: 'Sep 5 2024',
                            },
                        },
                        {
                            name: '.zcompdump-archlinux-5.9.zwc',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-r--r--r--',
                            size: 118616,
                            timestamp: {
                                shortHand: 'Sep 5 2024',
                            },
                        },
                        {
                            name: '.zcompdump-ogony-5.9',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 51172,
                            timestamp: {
                                shortHand: 'Jun 27 15:16',
                            },
                        },
                        {
                            name: '.zcompdump-ogony-5.9.zwc',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-r--r--r--',
                            size: 119832,
                            timestamp: {
                                shortHand: 'Jun 27 15:16',
                            },
                        },
                        {
                            name: '.zen',
                            type: 'directory',
                            ownership: 'kony/kony',
                            permissions: 'drwx------',
                            size: 4096,
                            timestamp: {
                                shortHand: 'Jul 11 16:09',
                            },
                        },
                        {
                            name: '.zprofile',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 165,
                            timestamp: {
                                shortHand: 'May 28 22:18',
                            },
                        },
                        {
                            name: '.zshenv',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 21,
                            timestamp: {
                                shortHand: 'Sep 7 2024',
                            },
                        },
                        {
                            name: '.zsh_history',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-------',
                            size: 395360,
                            timestamp: {
                                shortHand: 'Jul 11 17:09',
                            },
                        },
                        {
                            name: '.zshrc',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 1956,
                            timestamp: {
                                shortHand: 'May 29 19:59',
                            },
                        },
                        {
                            name: '.zshrc-backup',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 3996,
                            timestamp: {
                                shortHand: 'Sep 5 2024',
                            },
                        },
                        {
                            name: '.zshrc.save',
                            type: 'file',
                            ownership: 'kony/kony',
                            permissions: '-rw-r--r--',
                            size: 883,
                            timestamp: {
                                shortHand: 'Sep 9 2024',
                            },
                        },
                    ],
                },
            ],
        },
        {
            name: 'lib',
            type: 'file',
            ownership: 'root/root',
            permissions: 'lrwxrwxrwx',
            size: 7,
            timestamp: {
                shortHand: 'May 4 02:26',
            },
        },
        {
            name: 'lib64',
            type: 'file',
            ownership: 'root/root',
            permissions: 'lrwxrwxrwx',
            size: 7,
            timestamp: {
                shortHand: 'May 4 02:26',
            },
        },
        {
            name: 'lost+found',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwx------',
            size: 16384,
            timestamp: {
                shortHand: 'Sep 5 2024',
            },
        },
        {
            name: 'mnt',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwxr-xr-x',
            size: 4096,
            timestamp: {
                shortHand: 'Apr 8 2024',
            },
        },
        {
            name: 'opt',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwxr-xr-x',
            size: 4096,
            timestamp: {
                shortHand: 'Jul 8 18:01',
            },
        },
        {
            name: 'proc',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'dr-xr-xr-x',
            size: 0,
            timestamp: {
                shortHand: 'Jul 11 2025',
            },
        },
        {
            name: 'root',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwx------',
            size: 4096,
            timestamp: {
                shortHand: 'Jul 8 18:02',
            },
        },
        {
            name: 'run',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwxr-xr-x',
            size: 700,
            timestamp: {
                shortHand: 'Jul 11 2025',
            },
        },
        {
            name: 'sbin',
            type: 'file',
            ownership: 'root/root',
            permissions: 'lrwxrwxrwx',
            size: 7,
            timestamp: {
                shortHand: 'May 4 02:26',
            },
        },
        {
            name: 'srv',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwxr-xr-x',
            size: 4096,
            timestamp: {
                shortHand: 'Sep 5 2024',
            },
        },
        {
            name: 'sys',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'dr-xr-xr-x',
            size: 0,
            timestamp: {
                shortHand: 'Jul 11 16:57',
            },
        },
        {
            name: 'tmp',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwxrwxrwt',
            size: 760,
            timestamp: {
                shortHand: 'Jul 11 17:09',
            },
        },
        {
            name: 'usr',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwxr-xr-x',
            size: 4096,
            timestamp: {
                shortHand: 'Jul 11 12:57',
            },
        },
        {
            name: 'var',
            type: 'directory',
            ownership: 'root/root',
            permissions: 'drwxr-xr-x',
            size: 4096,
            timestamp: {
                shortHand: 'Jul 10 19:55',
            },
        },
    ],
};
