name: Frontend

on:
    push:
        branches: [main]

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    build:
        if: contains(github.event.head_commit.message, '[FRONTEND]')
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: oven-sh/setup-bun@v1

            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Install dependencies
              run: bun install
              working-directory: ./frontend

            - name: Build
              run: bun run build
              working-directory: ./frontend

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./frontend/out

    deploy:
        if: contains(github.event.head_commit.message, '[FRONTEND]')
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
